spring:
  datasource:
    url: jdbc:mysql://${prod-db.mysql.host}:${prod-db.mysql.port}/${prod-db.mysql.name}
    username: ${prod-db.mysql.username}
    password: ${prod-db.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 프로덕션 메일 설정
  mail:
    host: ${PROD_MAIL_HOST:smtp.gmail.com}
    port: ${PROD_MAIL_PORT:587}
    username: ${PROD_MAIL_USERNAME}
    password: ${PROD_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: create  # 첫 실행 후 validate로 변경 필요
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

# 프로덕션용 FastAPI URL
fastapi:
  url: ${FASTAPI_PROD_URL}  # 프로덕션 FastAPI 서버 URL

# 프로덕션용 OAuth 리다이렉트 URL 설정 (필요시)